version: 2

jobs:
    test:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn test
            - run: yarn build
